 09/04/2025 10:21:24 AM - INFO - BOT TELEGRAM YOUTUBE

 09/04/2025 10:21:24 AM - INFO - bot chamado
 09/04/2025 10:22:13 AM - INFO - usuario esta tentando fazer download
 09/04/2025 10:22:15 AM - INFO - FIZ_UM_MALWARE: https://youtu.be/4pobgFPm19c?si=_rY-xtWbi0HXw-hD
 09/04/2025 10:22:19 AM - INFO - o usuario pediu a opcao video
 09/04/2025 10:23:03 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\FIZ_UM_MALWARE.m4a
 09/04/2025 10:23:18 AM - INFO - ('Connection aborted.', timeout('The write operation timed out'))
 09/04/2025 10:39:39 AM - INFO - BOT TELEGRAM YOUTUBE

 09/04/2025 10:39:39 AM - INFO - bot chamado
 09/04/2025 10:39:57 AM - INFO - usuario esta tentando fazer download
 09/04/2025 10:39:59 AM - INFO - FIZ_UM_MALWARE: https://youtu.be/4pobgFPm19c?si=_rY-xtWbi0HXw-hD
 09/04/2025 10:40:01 AM - INFO - o usuario pediu a opcao video
 09/04/2025 10:40:51 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\FIZ_UM_MALWARE.m4a
 09/04/2025 10:41:20 AM - INFO - ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))
 09/04/2025 10:45:27 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request
 09/04/2025 10:45:27 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request

 09/04/2025 10:45:30 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:45:30 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:45:31 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:45:31 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:45:35 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:45:35 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:45:37 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:45:37 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:45:41 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:45:41 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:45:49 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:45:49 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:46:05 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:46:05 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:46:38 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:46:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:47:38 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:47:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:48:38 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:48:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:49:38 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:49:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:50:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:50:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:51:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:51:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:52:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:52:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:53:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:53:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:54:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:54:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:55:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 10:55:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 10:59:52 AM - INFO - BOT TELEGRAM YOUTUBE

 09/04/2025 10:59:52 AM - INFO - bot chamado
 09/04/2025 11:00:10 AM - INFO - usuario esta tentando fazer download
 09/04/2025 11:00:12 AM - INFO - FIZ_UM_MALWARE: https://youtu.be/4pobgFPm19c?si=_rY-xtWbi0HXw-hD
 09/04/2025 11:01:59 AM - INFO - o usuario pediu a opcao video
 09/04/2025 11:02:00 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\FIZ_UM_MALWARE.m4a
 09/04/2025 11:02:29 AM - INFO - ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))
 09/04/2025 11:03:21 AM - INFO - usuario esta tentando fazer download
 09/04/2025 11:03:22 AM - INFO - Moonlight_on_the_River: https://youtu.be/1VYbKamjB-4?si=JDefe5VzpQPTCIS6
 09/04/2025 11:03:25 AM - INFO - usuario pediu a opcao audio
 09/04/2025 11:03:25 AM - INFO - baixando audio...
 09/04/2025 11:03:33 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Moonlight_on_the_River.m4a
 09/04/2025 11:03:50 AM - INFO - audio enviado

 09/04/2025 11:05:16 AM - INFO - usuario esta tentando fazer download
 09/04/2025 11:05:18 AM - INFO - 2ZDinizz_-_Coisas_Que_N_o_Aprendi_Contigo__Clipe_Oficial____PATRONO: https://youtu.be/fAIlEcAtfGU?si=iyCMF1bbzFY3nBVX
 09/04/2025 11:05:21 AM - INFO - usuario pediu a opcao audio
 09/04/2025 11:05:21 AM - INFO - baixando audio...
 09/04/2025 11:05:26 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\2ZDinizz_-_Coisas_Que_N_o_Aprendi_Contigo__Clipe_Oficial____PATRONO.m4a
 09/04/2025 11:05:37 AM - INFO - audio enviado

 09/04/2025 11:08:13 AM - INFO - usuario esta tentando fazer download
 09/04/2025 11:08:15 AM - INFO - 04__Baco_Exu_do_Blues_-_20_Liga__es: https://youtu.be/Sq7pVppXesU?si=GMVKLMsH5GW4zwew
 09/04/2025 11:08:19 AM - INFO - usuario pediu a opcao audio
 09/04/2025 11:08:19 AM - INFO - baixando audio...
 09/04/2025 11:08:22 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\04__Baco_Exu_do_Blues_-_20_Liga__es.m4a
 09/04/2025 11:08:30 AM - INFO - audio enviado

 09/04/2025 11:59:07 AM - INFO - BOT TELEGRAM YOUTUBE

 09/04/2025 11:59:07 AM - INFO - bot chamado
 09/04/2025 11:59:50 AM - INFO - usuario esta tentando fazer download
 09/04/2025 11:59:52 AM - INFO - LinkedIn_para_PROGRAMADORES_iniciantes__guia_pr_tico_: https://youtu.be/umI7sAvUeZ8?si=0Nj3OV88bMvn90HE
 09/04/2025 11:59:58 AM - INFO - o usuario pediu a opcao video
 09/04/2025 12:01:07 PM - INFO - BOT TELEGRAM YOUTUBE

 09/04/2025 12:01:07 PM - INFO - bot chamado
 09/04/2025 12:01:14 PM - INFO - usuario esta tentando fazer download
 09/04/2025 12:01:16 PM - INFO - LinkedIn_para_PROGRAMADORES_iniciantes__guia_pr_tico_: https://youtu.be/umI7sAvUeZ8?si=0Nj3OV88bMvn90HE
 09/04/2025 12:01:18 PM - INFO - o usuario pediu a opcao video
 09/04/2025 12:06:40 PM - INFO - BOT TELEGRAM YOUTUBE

 09/04/2025 12:06:40 PM - INFO - bot chamado
 09/04/2025 12:06:45 PM - INFO - usuario esta tentando fazer download
 09/04/2025 12:06:47 PM - INFO - LinkedIn_para_PROGRAMADORES_iniciantes__guia_pr_tico_: https://youtu.be/umI7sAvUeZ8?si=0Nj3OV88bMvn90HE
 09/04/2025 12:06:51 PM - INFO - o usuario pediu a opcao video
 09/04/2025 12:06:51 PM - INFO - 'NoneType' object has no attribute 'strip'
 09/04/2025 12:15:29 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request
 09/04/2025 12:15:29 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request

 09/04/2025 12:15:33 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 12:15:33 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 12:15:33 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 12:15:33 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 12:15:38 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 12:15:38 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 12:15:40 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 12:15:40 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 12:15:44 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 12:15:44 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 09/04/2025 12:15:52 PM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 09/04/2025 12:15:52 PM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 09:34:11 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 09:34:11 AM - INFO - bot chamado
 11/04/2025 09:34:52 AM - INFO - usuario esta tentando fazer download
 11/04/2025 09:34:54 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 09:34:57 AM - INFO - o usuario pediu a opcao video
 11/04/2025 09:35:29 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\ALEE_-_PAG_O_Ft__KLISMAN.m4a
 11/04/2025 09:59:30 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 09:59:30 AM - INFO - bot chamado
 11/04/2025 09:59:38 AM - INFO - usuario esta tentando fazer download
 11/04/2025 09:59:39 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 09:59:42 AM - INFO - o usuario pediu a opcao video
 11/04/2025 10:00:02 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\ALEE_-_PAG_O_Ft__KLISMAN.m4a
 11/04/2025 11:02:21 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:02:21 AM - INFO - bot chamado
 11/04/2025 11:02:42 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:02:44 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:02:50 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:02:50 AM - INFO - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Unexpected end tag at byte offset 0
 11/04/2025 11:05:33 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:05:35 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:05:37 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:05:37 AM - INFO - A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Unexpected end tag at byte offset 0
 11/04/2025 11:12:50 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:12:50 AM - INFO - bot chamado
 11/04/2025 11:13:01 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:13:03 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:13:05 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:13:15 AM - ERROR - Infinity polling exception: 'Message' object has no attribute 'next'
 11/04/2025 11:13:15 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "c:\Users\paulo.welton\Desktop\bot_telegram_youtube\src\model\bot.py", line 36, in processar_escolha
    escolha = message.next.strip()
AttributeError: 'Message' object has no attribute 'next'

 11/04/2025 11:17:20 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:17:22 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:17:23 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:17:27 AM - ERROR - Infinity polling exception: 'Message' object has no attribute 'next'
 11/04/2025 11:17:27 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "c:\Users\paulo.welton\Desktop\bot_telegram_youtube\src\model\bot.py", line 36, in processar_escolha
    escolha = message.next.strip()
AttributeError: 'Message' object has no attribute 'next'

 11/04/2025 11:17:48 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:17:48 AM - INFO - bot chamado
 11/04/2025 11:17:52 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:17:54 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:17:56 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:18:38 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:18:38 AM - INFO - bot chamado
 11/04/2025 11:18:40 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:18:42 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:18:44 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:19:07 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:19:07 AM - INFO - bot chamado
 11/04/2025 11:19:30 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:19:32 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:19:35 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:19:38 AM - ERROR - Infinity polling exception: 6490586194
 11/04/2025 11:19:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "c:\Users\paulo.welton\Desktop\bot_telegram_youtube\src\model\bot.py", line 46, in processar_escolha
    bot.register_next_step_handler(message, enviar_video_via_email, user_data[chat_id])
KeyError: 6490586194

 11/04/2025 11:35:49 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request
 11/04/2025 11:35:49 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request

 11/04/2025 11:35:53 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:35:53 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:35:54 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:35:54 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:35:58 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:35:58 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:36:00 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:36:00 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:36:04 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:36:04 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:36:12 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:36:12 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:36:28 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:36:28 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:37:01 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:37:01 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:38:01 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:38:01 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:39:01 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:39:01 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:40:01 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:40:01 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:41:02 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:41:02 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:42:02 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:42:02 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:43:02 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:43:02 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:44:02 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:44:02 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:45:02 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:45:02 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:46:03 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:46:03 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:47:03 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:47:03 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:48:03 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:48:03 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:49:03 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:49:03 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:50:03 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:50:03 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:51:04 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:51:04 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:52:04 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:52:04 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:53:04 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 11/04/2025 11:53:04 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 11/04/2025 11:55:51 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:55:51 AM - INFO - bot chamado
 11/04/2025 11:56:10 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:56:12 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:56:16 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:56:23 AM - ERROR - Infinity polling exception: 6490586194
 11/04/2025 11:56:23 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 148, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "c:\Users\paulo.welton\Desktop\bot_telegram_youtube\src\model\bot.py", line 46, in processar_escolha
    bot.register_next_step_handler(msg, enviar_video_via_email, user_data[chat_id])
KeyError: 6490586194

 11/04/2025 11:58:34 AM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 11:58:34 AM - INFO - bot chamado
 11/04/2025 11:59:03 AM - INFO - usuario esta tentando fazer download
 11/04/2025 11:59:04 AM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 11:59:06 AM - INFO - o usuario pediu a opcao video
 11/04/2025 11:59:36 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\ALEE_-_PAG_O_Ft__KLISMAN.m4a
 11/04/2025 12:07:51 PM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 12:07:51 PM - INFO - bot chamado
 11/04/2025 12:08:03 PM - INFO - usuario esta tentando fazer download
 11/04/2025 12:08:04 PM - INFO - ALEE_-_PAG_O_Ft__KLISMAN: https://youtu.be/EfJMGfM3c5Q?si=v_LBRmUKMXrfWB8I
 11/04/2025 12:08:09 PM - INFO - o usuario pediu a opcao video
 11/04/2025 12:08:18 PM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\ALEE_-_PAG_O_Ft__KLISMAN.m4a
 11/04/2025 12:58:34 PM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 12:58:34 PM - INFO - bot chamado
 11/04/2025 12:58:36 PM - ERROR - Error: 'module' object is not callable
 11/04/2025 12:58:36 PM - INFO - tarefa finalizada

 11/04/2025 12:59:35 PM - INFO - BOT TELEGRAM YOUTUBE

 11/04/2025 12:59:35 PM - INFO - bot chamado
 11/04/2025 12:59:36 PM - ERROR - Error: 'module' object is not callable
 11/04/2025 12:59:36 PM - INFO - tarefa finalizada

 14/04/2025 09:33:43 AM - INFO - BOT TELEGRAM YOUTUBE

 14/04/2025 09:33:43 AM - INFO - bot chamado
 14/04/2025 09:35:12 AM - INFO - usuario esta tentando fazer download
 14/04/2025 09:35:14 AM - INFO - WIU_-_CHICK: https://youtu.be/xyToc2r1SWw?si=hUXpcqxsNqbX5Fi1
 14/04/2025 09:35:22 AM - INFO - usuario pediu a opcao audio
 14/04/2025 09:35:22 AM - INFO - baixando audio...
 14/04/2025 09:35:26 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\WIU_-_CHICK.m4a
 14/04/2025 09:35:34 AM - INFO - audio enviado

 14/04/2025 09:37:13 AM - INFO - usuario esta tentando fazer download
 14/04/2025 09:37:15 AM - INFO - Post_Malone__Swae_Lee_-_Sunflower__Spider-Man__Into_the_Spider-Verse___Official_Video_: https://youtu.be/ApXoWvfEYVU?si=qeGZfSiuiXn0y-uH
 14/04/2025 09:37:17 AM - INFO - usuario pediu a opcao audio
 14/04/2025 09:37:17 AM - INFO - baixando audio...
 14/04/2025 09:37:21 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Post_Malone__Swae_Lee_-_Sunflower__Spider-Man__Into_the_Spider-Verse___Official_Video_.m4a
 14/04/2025 09:37:28 AM - INFO - audio enviado

 14/04/2025 09:38:09 AM - INFO - usuario esta tentando fazer download
 14/04/2025 09:38:10 AM - INFO - Vacations_-_Telephones: https://youtu.be/y7B6Z-_-Bcc?si=JLCXoNKXaX32k1xG
 14/04/2025 09:38:13 AM - INFO - usuario pediu a opcao audio
 14/04/2025 09:38:13 AM - INFO - baixando audio...
 14/04/2025 09:38:17 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Vacations_-_Telephones.m4a
 14/04/2025 09:38:32 AM - INFO - audio enviado

 14/04/2025 09:39:15 AM - INFO - usuario esta tentando fazer download
 14/04/2025 09:39:17 AM - INFO - Como_um_menino_fugindo_de_casa_causou_a_era_da_Intelig_ncia_Artificial: https://youtu.be/mBqfY_TX_8o?si=6soeBPfTwd1zRz8X
 14/04/2025 09:39:20 AM - INFO - o usuario pediu a opcao video
 14/04/2025 09:40:48 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\Como_um_menino_fugindo_de_casa_causou_a_era_da_Intelig_ncia_Artificial.m4a
 14/04/2025 10:45:25 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request
 14/04/2025 10:45:25 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by setWebhook request

 14/04/2025 10:45:29 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 14/04/2025 10:45:29 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 14/04/2025 10:45:30 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 14/04/2025 10:45:30 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 14/04/2025 10:45:34 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 14/04/2025 10:45:34 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 14/04/2025 10:45:36 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
 14/04/2025 10:45:36 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first

 14/04/2025 12:54:41 PM - INFO - BOT TELEGRAM YOUTUBE

 14/04/2025 12:54:41 PM - INFO - bot chamado
 14/04/2025 12:54:44 PM - INFO - usuario esta tentando fazer download
 14/04/2025 12:54:46 PM - INFO - O_mentor_OCULTO_de_Raiam_Santos__M_rio_Schwartzman_: https://youtu.be/kqCnUgdnYUE?si=HW0EYvoeoTezlmpe
 14/04/2025 12:54:49 PM - INFO - o usuario pediu a opcao video
 14/04/2025 12:55:31 PM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\video\O_mentor_OCULTO_de_Raiam_Santos__M_rio_Schwartzman_.m4a
 15/04/2025 10:37:15 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 10:37:15 AM - INFO - bot chamado
 15/04/2025 10:48:38 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
 15/04/2025 10:48:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

 15/04/2025 10:48:38 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
 15/04/2025 10:48:38 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

 15/04/2025 10:48:39 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
 15/04/2025 10:48:39 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

 15/04/2025 10:48:40 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
 15/04/2025 10:48:40 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

 15/04/2025 10:48:42 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
 15/04/2025 10:48:42 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

 15/04/2025 10:48:46 AM - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized
 15/04/2025 10:48:46 AM - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 109, in raise_exceptions
    raise self.exception_info
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\util.py", line 91, in run
    task(*args, **kwargs)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 649, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 623, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 321, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\paulo.welton\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 401. Description: Unauthorized

 15/04/2025 10:49:04 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 10:49:04 AM - INFO - bot chamado
 15/04/2025 10:49:04 AM - ERROR - Error: remove_webhook() got an unexpected keyword argument 'drop_pending_updates'
 15/04/2025 10:49:04 AM - INFO - tarefa finalizada

 15/04/2025 10:49:04 AM - INFO - bot chamado
 15/04/2025 10:49:29 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 10:49:29 AM - INFO - bot chamado
 15/04/2025 10:49:29 AM - ERROR - Error: remove_webhook() got an unexpected keyword argument 'drop_pending_updates'
 15/04/2025 10:49:29 AM - INFO - tarefa finalizada

 15/04/2025 10:49:29 AM - INFO - bot chamado
 15/04/2025 10:49:38 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 10:49:38 AM - INFO - bot chamado
 15/04/2025 10:50:51 AM - INFO - usuario esta tentando fazer download
 15/04/2025 10:50:53 AM - INFO - Young_-_Vacations__Official_Lyric_Video_: https://youtu.be/nK61uvq5tX4?si=newKRrVKa1XfPKKi
 15/04/2025 10:50:55 AM - INFO - usuario pediu a opcao audio
 15/04/2025 10:50:56 AM - INFO - usuario pediu a opcao audio
 15/04/2025 10:50:56 AM - INFO - baixando audio...
 15/04/2025 10:50:56 AM - INFO - baixando audio...
 15/04/2025 10:50:59 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Young_-_Vacations__Official_Lyric_Video_.m4a
 15/04/2025 10:51:00 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Young_-_Vacations__Official_Lyric_Video_.m4a
 15/04/2025 10:51:08 AM - INFO - audio enviado

 15/04/2025 10:51:08 AM - INFO - audio enviado

 15/04/2025 10:51:08 AM - INFO - mensagem não deletada
 15/04/2025 10:58:38 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 10:58:38 AM - INFO - bot chamado
 15/04/2025 10:59:03 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 10:59:03 AM - INFO - bot chamado
 15/04/2025 11:00:27 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 11:00:27 AM - INFO - bot chamado
 15/04/2025 11:00:58 AM - INFO - usuario esta tentando fazer download
 15/04/2025 11:01:00 AM - INFO - Intro: https://youtu.be/e8yxF-0qk8o?si=Vn5Czp9JBh072uvY
 15/04/2025 11:01:06 AM - INFO - usuario pediu a opcao audio
 15/04/2025 11:01:06 AM - INFO - baixando audio...
 15/04/2025 11:01:08 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Intro.m4a
 15/04/2025 11:01:12 AM - INFO - audio enviado

 15/04/2025 11:14:31 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 11:14:31 AM - INFO - bot chamado
 15/04/2025 11:21:46 AM - INFO - BOT TELEGRAM YOUTUBE

 15/04/2025 11:21:46 AM - INFO - bot chamado
 28/04/2025 10:15:21 AM - INFO - BOT TELEGRAM YOUTUBE

 28/04/2025 10:15:21 AM - INFO - bot chamado
 28/04/2025 10:15:39 AM - INFO - usuario esta tentando fazer download
 28/04/2025 10:15:40 AM - INFO - Lovers_Rock: https://youtu.be/j_sG_Juncn8?si=thlYBA0mDEfwJllE
 28/04/2025 10:15:43 AM - INFO - usuario pediu a opcao audio
 28/04/2025 10:15:43 AM - INFO - baixando audio...
 28/04/2025 10:15:45 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Lovers_Rock.m4a
 28/04/2025 10:15:56 AM - INFO - audio enviado

 28/04/2025 10:16:02 AM - INFO - usuario esta tentando fazer download
 28/04/2025 10:16:03 AM - INFO - TV_Girl_-_Blue_Hair: https://youtu.be/PzIXNqpCug0?si=_CoCn5XbFksxqxOp
 28/04/2025 10:16:23 AM - INFO - usuario pediu a opcao audio
 28/04/2025 10:16:23 AM - INFO - baixando audio...
 28/04/2025 10:16:25 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\TV_Girl_-_Blue_Hair.m4a
 28/04/2025 10:16:41 AM - INFO - audio enviado

 28/04/2025 10:16:43 AM - INFO - usuario esta tentando fazer download
 28/04/2025 10:16:45 AM - INFO - Lil_Tecca_-_Dark_Thoughts__Official_Video_: https://youtu.be/Xtq_A2NnHKQ?si=GQVn12G8MPKnXluf
 28/04/2025 10:16:47 AM - INFO - usuario pediu a opcao audio
 28/04/2025 10:16:48 AM - INFO - baixando audio...
 28/04/2025 10:16:49 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Lil_Tecca_-_Dark_Thoughts__Official_Video_.m4a
 28/04/2025 10:16:59 AM - INFO - audio enviado

 28/04/2025 10:17:15 AM - INFO - usuario esta tentando fazer download
 28/04/2025 10:17:17 AM - INFO - Matu__-_Like_This___Bonus_Track_: https://youtu.be/81z0TwCVyfs?si=H1cz1yEzZyFIKjij
 28/04/2025 10:17:24 AM - INFO - usuario pediu a opcao audio
 28/04/2025 10:17:24 AM - INFO - baixando audio...
 28/04/2025 10:17:25 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Matu__-_Like_This___Bonus_Track_.m4a
 28/04/2025 10:17:36 AM - INFO - audio enviado

 28/04/2025 10:17:37 AM - INFO - usuario esta tentando fazer download
 28/04/2025 10:17:39 AM - INFO - 02_niLL_-_Regras_da_Loja_Part__BK___Prod__Crimenow_: https://youtu.be/-jyMoCaTW_Q?si=bu1dPjHa4hRiT11T
 28/04/2025 10:17:41 AM - INFO - usuario pediu a opcao audio
 28/04/2025 10:17:41 AM - INFO - baixando audio...
 28/04/2025 10:17:43 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\02_niLL_-_Regras_da_Loja_Part__BK___Prod__Crimenow_.m4a
 28/04/2025 10:17:55 AM - INFO - audio enviado

 28/04/2025 10:18:12 AM - INFO - usuario esta tentando fazer download
 28/04/2025 10:18:14 AM - INFO - Los_Hermanos_-__ltimo_Romance: https://youtu.be/6w3uAKabfFg?si=B_yzZnzyLjYcQ4ga
 28/04/2025 10:18:16 AM - INFO - usuario pediu a opcao audio
 28/04/2025 10:18:16 AM - INFO - baixando audio...
 28/04/2025 10:18:18 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Los_Hermanos_-__ltimo_Romance.m4a
 28/04/2025 10:18:32 AM - INFO - audio enviado

 30/05/2025 10:54:34 AM - INFO - BOT TELEGRAM YOUTUBE

 30/05/2025 10:54:34 AM - INFO - bot chamado
 30/05/2025 10:55:00 AM - INFO - usuario esta tentando fazer download
 30/05/2025 10:55:02 AM - INFO - BK___prod__Paulo_DK__-_Am_m__Am_m__Visualizer_: https://youtu.be/NE0NnTFohDU?si=b-OcAygI8Tj6mERR
 30/05/2025 10:55:06 AM - INFO - usuario pediu a opcao audio
 30/05/2025 10:55:06 AM - INFO - baixando audio...
 30/05/2025 10:55:09 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\BK___prod__Paulo_DK__-_Am_m__Am_m__Visualizer_.m4a
 30/05/2025 10:55:16 AM - INFO - audio enviado

 30/05/2025 11:09:13 AM - INFO - usuario esta tentando fazer download
 30/05/2025 11:09:15 AM - INFO - FBC_-_Se_Eu_N_o_Te_Cantar__Clipe_Oficial_: https://youtu.be/3mclQ4V28JQ?si=GMaEiLah7vRseZkD
 30/05/2025 11:09:20 AM - INFO - usuario pediu a opcao audio
 30/05/2025 11:09:20 AM - INFO - baixando audio...
 30/05/2025 11:09:23 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\FBC_-_Se_Eu_N_o_Te_Cantar__Clipe_Oficial_.m4a
 30/05/2025 11:09:31 AM - INFO - audio enviado

 17/06/2025 09:01:25 AM - INFO - BOT TELEGRAM YOUTUBE

 17/06/2025 09:01:25 AM - INFO - bot chamado
 17/06/2025 09:11:07 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:11:08 AM - INFO - Teto_-_YES_OR_NO: https://youtu.be/21XWVPwMcas?si=kZFj01l3TSPoHZey
 17/06/2025 09:11:14 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:11:15 AM - INFO - baixando audio...
 17/06/2025 09:11:19 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Teto_-_YES_OR_NO.m4a
 17/06/2025 09:11:27 AM - INFO - audio enviado

 17/06/2025 09:12:08 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:12:10 AM - INFO - Pra_Ningu_m_Se_Esconder: https://youtu.be/EM3rQzbQ5yU?si=IVfA40NM4zqowTTJ
 17/06/2025 09:12:12 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:12:13 AM - INFO - baixando audio...
 17/06/2025 09:12:18 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Pra_Ningu_m_Se_Esconder.m4a
 17/06/2025 09:12:28 AM - INFO - audio enviado

 17/06/2025 09:12:41 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:12:43 AM - INFO - Todo_Errado: https://youtu.be/95hoOsyMs3E?si=Hn0Ull5xKykglfvC
 17/06/2025 09:12:45 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:12:45 AM - INFO - baixando audio...
 17/06/2025 09:12:49 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Todo_Errado.m4a
 17/06/2025 09:12:58 AM - INFO - audio enviado

 17/06/2025 09:13:01 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:13:02 AM - INFO - Voc__N_o_Me_Ensinou_A_Te_Esquecer: https://youtu.be/wwI12iiUsRY?si=gwesT-ut7jnTjC-Y
 17/06/2025 09:13:07 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:13:08 AM - INFO - baixando audio...
 17/06/2025 09:13:12 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Voc__N_o_Me_Ensinou_A_Te_Esquecer.m4a
 17/06/2025 09:13:22 AM - INFO - audio enviado

 17/06/2025 09:13:27 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:13:28 AM - INFO - N_A_D_A_B_O_M_: https://youtu.be/4Zme4KInm2I?si=NlYyjc2pEiE4doy_
 17/06/2025 09:13:35 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:13:36 AM - INFO - baixando audio...
 17/06/2025 09:13:40 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\N_A_D_A_B_O_M_.m4a
 17/06/2025 09:13:52 AM - INFO - audio enviado

 17/06/2025 09:13:54 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:13:56 AM - INFO - SURF: https://youtu.be/oz0a5ouYY3A?si=LqnOBIAy7LK5Rvu8
 17/06/2025 09:13:59 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:13:59 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:13:59 AM - INFO - baixando audio...
 17/06/2025 09:13:59 AM - INFO - baixando audio...
 17/06/2025 09:14:03 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\SURF.m4a
 17/06/2025 09:14:04 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\SURF.m4a
 17/06/2025 09:14:10 AM - INFO - audio enviado

 17/06/2025 09:14:13 AM - INFO - audio enviado

 17/06/2025 09:14:13 AM - INFO - mensagem não deletada
 17/06/2025 09:15:56 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:15:57 AM - INFO - ESTRESSE: https://youtu.be/rcMoI-p3-3A?si=Ytn4LexYc4IpKcg0
 17/06/2025 09:16:01 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:16:01 AM - INFO - baixando audio...
 17/06/2025 09:16:04 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\ESTRESSE.m4a
 17/06/2025 09:16:11 AM - INFO - audio enviado

 17/06/2025 09:16:16 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:16:17 AM - INFO - _LTIMA_VEZ: https://youtu.be/ATrFio56WDc?si=whC0VX1q4XaNqz6S
 17/06/2025 09:16:22 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:16:22 AM - INFO - baixando audio...
 17/06/2025 09:16:25 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\_LTIMA_VEZ.m4a
 17/06/2025 09:16:33 AM - INFO - audio enviado

 17/06/2025 09:17:14 AM - INFO - usuario esta tentando fazer download
 17/06/2025 09:17:16 AM - INFO - 06__Baco_Exu_do_Blues_-_Samba_in_Paris__ft__Gloria_Groove_: https://youtu.be/4iKtTmnHojU?si=4rWluE38Xl120Xcw
 17/06/2025 09:17:19 AM - INFO - usuario pediu a opcao audio
 17/06/2025 09:17:20 AM - INFO - baixando audio...
 17/06/2025 09:17:24 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\06__Baco_Exu_do_Blues_-_Samba_in_Paris__ft__Gloria_Groove_.m4a
 17/06/2025 09:17:37 AM - INFO - audio enviado

 03/07/2025 09:21:47 AM - INFO - BOT TELEGRAM YOUTUBE

 03/07/2025 09:21:47 AM - INFO - bot chamado
 03/07/2025 09:54:22 AM - INFO - usuario esta tentando fazer download
 03/07/2025 09:54:23 AM - INFO - Yunk_Vino_-_Leans_Pt_2: https://youtu.be/nK0g70RVjtU?si=KbRCXIAtIfQn1vut
 03/07/2025 09:54:28 AM - INFO - usuario pediu a opcao audio
 03/07/2025 09:54:28 AM - INFO - baixando audio...
 03/07/2025 09:54:31 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Yunk_Vino_-_Leans_Pt_2.m4a
 03/07/2025 09:54:39 AM - INFO - audio enviado

 03/07/2025 09:55:20 AM - INFO - usuario esta tentando fazer download
 03/07/2025 09:55:21 AM - INFO - Yunk_Vino-_Campari__LETRA_: https://youtu.be/1eD5d4fid-Q?si=lImiwAnh6L6OpVAK
 03/07/2025 09:55:30 AM - INFO - usuario pediu a opcao audio
 03/07/2025 09:55:31 AM - INFO - baixando audio...
 03/07/2025 09:55:34 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Yunk_Vino-_Campari__LETRA_.m4a
 03/07/2025 09:55:39 AM - INFO - audio enviado

 03/07/2025 09:59:25 AM - INFO - usuario esta tentando fazer download
 03/07/2025 09:59:26 AM - INFO - Gilsons_-_Love_Love__Lyric_v_deo_: https://youtu.be/2EGXgmoYtgA?si=59x8Nu8z1VwryQ7a
 03/07/2025 09:59:37 AM - INFO - usuario pediu a opcao audio
 03/07/2025 09:59:37 AM - INFO - baixando audio...
 03/07/2025 09:59:41 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Gilsons_-_Love_Love__Lyric_v_deo_.m4a
 03/07/2025 09:59:50 AM - INFO - audio enviado

 03/07/2025 09:59:56 AM - INFO - usuario esta tentando fazer download
 03/07/2025 09:59:58 AM - INFO - Baco_Exu_do_Blues_-_999__Prod__Mazili___WebClipe_: https://youtu.be/K5yGZRjXzgM?si=8v7-qieEF_Fgqx6J
 03/07/2025 10:00:11 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:00:11 AM - INFO - baixando audio...
 03/07/2025 10:00:15 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Baco_Exu_do_Blues_-_999__Prod__Mazili___WebClipe_.m4a
 03/07/2025 10:00:25 AM - INFO - audio enviado

 03/07/2025 10:00:27 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:00:28 AM - INFO - E_Eu_N_o_Obedeci: https://youtu.be/HZ6gRfRVw3s?si=ETgn3U1TuTTr3gAz
 03/07/2025 10:00:32 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:00:32 AM - INFO - baixando audio...
 03/07/2025 10:00:37 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\E_Eu_N_o_Obedeci.m4a
 03/07/2025 10:00:47 AM - INFO - audio enviado

 03/07/2025 10:01:12 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:01:14 AM - INFO - 4__Solo__Videoclipe_oficial_: https://youtu.be/6jojd0r9_rk?si=DgOIXFUoWz8c7UMA
 03/07/2025 10:01:28 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:01:28 AM - INFO - baixando audio...
 03/07/2025 10:01:31 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\4__Solo__Videoclipe_oficial_.m4a
 03/07/2025 10:01:38 AM - INFO - audio enviado

 03/07/2025 10:01:40 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:01:42 AM - INFO - 3___Djonga_-_Esquim_: https://youtu.be/0vWoKiCmhn4?si=5VmhqcqhDSJlfmRW
 03/07/2025 10:02:40 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:02:41 AM - INFO - baixando audio...
 03/07/2025 10:02:45 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\3___Djonga_-_Esquim_.m4a
 03/07/2025 10:02:55 AM - INFO - audio enviado

 03/07/2025 10:03:51 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:03:52 AM - WARNING - ANDROID_VR client returned: This video is not available
 03/07/2025 10:03:52 AM - WARNING - Switching to client: TV
 03/07/2025 10:03:59 AM - WARNING - ANDROID_VR client returned: This video is not available
 03/07/2025 10:03:59 AM - WARNING - Switching to client: TV
 03/07/2025 10:04:01 AM - INFO - _Here_Comes_a_Thought____Steven_Universe___Cartoon_Network: https://youtu.be/dHg50mdODFM?si=QsD_ySSbF-KJHHKQ
 03/07/2025 10:04:07 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:04:08 AM - INFO - baixando audio...
 03/07/2025 10:04:08 AM - WARNING - ANDROID_VR client returned: This video is not available
 03/07/2025 10:04:08 AM - WARNING - Switching to client: TV
 03/07/2025 10:04:14 AM - ERROR - erro ao baixar video: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/e12fbea4/player_ias.vflset/en_US/base.js
 03/07/2025 10:10:16 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:10:18 AM - INFO - Caio_Ocean____F__meu_levado_: https://youtu.be/jsOU47lsmRg?si=PEnqubBZ3L4J7mVv
 03/07/2025 10:10:22 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:10:23 AM - INFO - baixando audio...
 03/07/2025 10:10:25 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Caio_Ocean____F__meu_levado_.m4a
 03/07/2025 10:10:30 AM - INFO - audio enviado

 03/07/2025 10:11:02 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:11:04 AM - INFO - Filipe_Ret_-_Acima_de_Mim_S__Deus___Clipe_Oficial_: https://youtu.be/UYKrwYJzZFw?si=A71ifN5KFU_jk4U3
 03/07/2025 10:11:11 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:11:11 AM - INFO - baixando audio...
 03/07/2025 10:11:14 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Filipe_Ret_-_Acima_de_Mim_S__Deus___Clipe_Oficial_.m4a
 03/07/2025 10:11:20 AM - INFO - audio enviado

 03/07/2025 10:12:24 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:12:24 AM - INFO - baixando audio...
 03/07/2025 10:12:27 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Filipe_Ret_-_Acima_de_Mim_S__Deus___Clipe_Oficial_.m4a
 03/07/2025 10:12:33 AM - INFO - audio enviado

 03/07/2025 10:12:51 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:12:52 AM - WARNING - ANDROID_VR client returned: This video is not available
 03/07/2025 10:12:52 AM - WARNING - Switching to client: TV
 03/07/2025 10:12:55 AM - WARNING - ANDROID_VR client returned: This video is not available
 03/07/2025 10:12:55 AM - WARNING - Switching to client: TV
 03/07/2025 10:12:57 AM - INFO - _Here_Comes_a_Thought____Steven_Universe___Cartoon_Network: https://youtu.be/dHg50mdODFM?si=QsD_ySSbF-KJHHKQ
 03/07/2025 10:13:02 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:13:02 AM - INFO - baixando audio...
 03/07/2025 10:13:03 AM - WARNING - ANDROID_VR client returned: This video is not available
 03/07/2025 10:13:03 AM - WARNING - Switching to client: TV
 03/07/2025 10:13:08 AM - ERROR - erro ao baixar video: get_throttling_function_name: could not find match for multiple in https://youtube.com/s/player/e12fbea4/player_ias.vflset/en_US/base.js
 03/07/2025 10:23:05 AM - INFO - BOT TELEGRAM YOUTUBE

 03/07/2025 10:23:05 AM - INFO - bot chamado
 03/07/2025 10:23:07 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:23:09 AM - INFO - DERXAN_-_OQ_C__FEZ__part__MALU: https://youtu.be/9MHmmPSsoYs?si=CaboNY3Cxgxu9QfE
 03/07/2025 10:23:12 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:23:12 AM - INFO - baixando audio...
 03/07/2025 10:23:15 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\DERXAN_-_OQ_C__FEZ__part__MALU.m4a
 03/07/2025 10:23:22 AM - INFO - audio enviado

 03/07/2025 10:24:11 AM - INFO - usuario esta tentando fazer download
 03/07/2025 10:24:13 AM - INFO - Derxan_-_ELIS_REGINA_part__MALU: https://youtu.be/C3j-UM72vLk?si=a8Vo1GoER74VMEdC
 03/07/2025 10:24:16 AM - INFO - usuario pediu a opcao audio
 03/07/2025 10:24:16 AM - INFO - baixando audio...
 03/07/2025 10:24:19 AM - INFO - caminho: C:\Users\paulo.welton\Desktop\bot_telegram_youtube\audio\Derxan_-_ELIS_REGINA_part__MALU.m4a
 03/07/2025 10:24:25 AM - INFO - audio enviado

